Workaround for weird bug caused by JDK version mismatch
Characteristic exception: java.lang.NoSuchMethodError:
java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;

If you see that, you need THIS commit. (It's because JDK 9 moved exactly
where the flip() method of ByteBuffer is implemented, resulting in a
signature change. See https://stackoverflow.com/q/61267495/301832 for
more info.)